### ISSUE TITLE
Command `mines`: First click may reveal a mine

### ISSUE THREAD

**Issue by FungiOfDeath** [TheSorton/Arisubot#2]
In most minesweeper games, the first click is guaranteed to not hit a mine.

## Suggested Solution
Reveal a single non-mine space at the start. This can be done by removing the spoiler on one of the non-mine spaces.

### Problems with this solution
The lack of spoiler may cause problems with the spacing. Spacing should be tested in both `cozy` and `compact` modes.

**Comment by TheSorton** [comment]
Spacing would be an easy fix since I can use blank characters with markdown. The issue arises with the module I'm using for the game. I'm using [this](https://github.com/jozsefsallai/discord.js-minesweeper). It doesn't have a way to not spoiler an emoji that isnt a mine. 

I'm probably going to write my own way of doing what that module does and add stuff like this.

It won't come immediately so don't hold your breath. Probably after I'm done with the bot completely and I'm able to just commit fixes instead of new features. For now though, just kinda have to cope with it. 

I'll make a project for this.

**Comment by jozsefsallai** [comment]
Hey! thanks for checking out my lib! 
I like your idea @FungiOfDeath, I should have thought of that when I made the module.
You can feel free to make a PR and I'll gladly merge it if you want, @TheSorton. I think passing a new boolean option to the minesweeper constructor would be a good deal (so that people can choose if they want this or not).

If you don't have time to make a PR, I can do that myself, and I'll credit both of you for bringing this to my attention in the comments of the file and the commit.

**Comment by TheSorton** [comment]
> If you don't have time to make a PR, I can do that myself, and I'll credit both of you for bringing this to my attention in the comments of the file and the commit.

That'd be a big help. I'm new to JavaScript and haven't even touched TypeScript. The bot is more of a learning project than anything. If you do it, please reference this issue so I can close it.

**Comment by jozsefsallai** [comment]
Midway through I realized that we won't actually have that many issues with the spaces (although some still *might* appear, in which case I'll fix them). So the new version is `discord.js-minesweeper@1.0.4-b`, it has a new option called `revealFirstCell` (which is false by default), which does what you guys wanted. Usage is pretty simple:

```js
const m = new Minesweeper({
  // ... other opts
  revealFirstCell: true
});
```

I'm kind of iffy about the spacing when the revealed cell is the very first cell of the matrix `(x: 0, y: 0)`, since discord messages can't start with a space (they can but spaces will be trimmed). This is all I had time for right now (birthday is busy), but if this issue does occur, I'll add a check and use a unicode space where necessary.

**Comment by TheSorton** [comment]
Thanks a lot! I'll be sure to implement this.
